- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/ProviderApplication.java
- spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryAutoConfiguration.java
- spring-cloud-alibaba-nacos-discovery/src/main/resources/META-INF/spring.factories
- spring-cloud-alicloud-ans/src/main/java/org/springframework/cloud/alicloud/ans/AnsAutoConfiguration.java
- spring-cloud-alicloud-ans/src/main/resources/META-INF/spring.factories
make @EnableDiscoveryClient Optional
#333 
delete  org.springframework.cloud.client.discovery.EnableDiscoveryClient Configuration in spring.factories , and add @AutoConfigureAfter(AutoServiceRegistrationAutoConfiguration.class) Annotation
delete @EnableDiscoveryClient in spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example, and start the application.it works
none
> Fixes #333, make @EnableDiscoveryClient Optional

- spring-cloud-alibaba-examples/oss-example/readme-zh.md
- spring-cloud-alibaba-examples/oss-example/readme.md
- spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md
- spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/application.properties
- spring-cloud-alibaba-examples/sms-example/readme-zh.md
- spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/endpoint/SentinelEndpointAutoConfiguration.java
- spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/endpoint/SentinelHealthIndicator.java
- spring-cloud-alibaba-sentinel/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-alibaba-sentinel/src/test/java/org/springframework/cloud/alibaba/sentinel/endpoint/SentinelHealthIndicatorTests.java
Hi, I'm a beginner of **SpringCloud**, like the easy use of **SCA** and start to learn and use it recently.
I find this issue and have a try, PTAL.
How to check the health of different DataSource, I haven't thought out a good idea so far, 
maybe we need to add check method in `AbstractDataSource` interface? not quite sure.
Could you please give some suggestions?
@fangjian0423 @sczyh30 
Fixes #265
Add `SentinelHealthIndicator` class extends `AbstractHealthIndicator` and implement the `doHealthCheck` method.
Check the status of Sentinel Dashboard by sending a heartbeat message to it.
Add `SentinelHealthIndicatorTests` and run test cases.
Run sentinel-core-example, modify `application.properties`, visit `http://localhost:18083/actuator/health` and check the result.
There are some typos in md …
> Add HealthIndicator in Sentinel Starter

- spring-cloud-alibaba-examples/rocketmq-example/readme-zh.md
- spring-cloud-alibaba-examples/rocketmq-example/readme.md
- spring-cloud-stream-binder-rocketmq/src/test/java/org/springframework/cloud/stream/binder/rocketmq/RocketMQAutoConfigurationTests.java
把过时的rocketmq的nameServer的地址配置名称修正为当前使用的配置名称
> 把过时的rocketmq的nameServer的地址配置名称修正为当前使用的配置名称

- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-with-spring-cloud-config-example/pom.xml
- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-with-spring-cloud-config-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/GetConfigController.java
- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-with-spring-cloud-config-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/NacosDiscoverySpringConfigApplication.java
- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-with-spring-cloud-config-example/src/main/resources/application.yml
- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-with-spring-cloud-config-example/src/main/resources/bootstrap.yml
- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/pom.xml
- spring-cloud-alibaba-nacos-discovery/pom.xml
- spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/configclient/NacosConfigServerAutoConfiguration.java
- spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/configclient/NacosDiscoveryClientConfigServiceBootstrapConfiguration.java
- spring-cloud-alibaba-nacos-discovery/src/main/resources/META-INF/spring.factories
Currentlly, spring-cloud-alibaba-nacos-discovery does not support looking up config-server URL via nacos discovery. Support this feature as Consul/Eureka like.
Fixes #708 
Add two configurations for looking up config-server URL via nacos discovery.
example for looking up config-server URL via nacos will be uploaded later. I tried it locally, runs well
here is the link for example:
https://github.com/JevonYang/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-with-spring-cloud-config-example
> Configuration for looking up config-server URL via nacos discovery

- spring-cloud-alibaba-examples/acm-example/acm-local-example/src/main/java/com/alibaba/cloud/examples/EchoController.java
Make the example app automatically refresh value from acm config server
by adding `@RefreshScope` annotation.
As indicated by the readme-zh.md of acm-local-example in spring-cloud-alibaba-examples.  The example app should automatically refresh the value `user.id` which is fetched from acm server.  The original code failed to do that and this PR fixes it.
NONE
Adding `@RefreshScope` annotation.
Just run acm-local-example, change the configurations from acm server and see if the value in the app changes.
NONE
> Fix acm-local-example

- spring-cloud-alibaba-examples/acm-example/acm-local-example/pom.xml
- spring-cloud-alibaba-examples/acm-example/acm-local-example/src/main/resources/bootstrap.properties
As indicated by the readme-zh.md of acm-local-example in spring-cloud-alibaba-examples.We can use localhost:18089/actuator/acm to vie health status of acm. The original cod failed to do that and this PR fixed it
None
Adding spring-boot-starter-actuator to pom.xml and adding management.endpoints.web.exposure.include=* to bootstrap.properties
Just start up your program and enter http://localhost:18089/actuator/acm
None
> View acm's health interface through the URL

- spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/AcmAutoConfiguration.java
- spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/bootstrap/AcmPropertySourceLocator.java
- spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/endpoint/AcmEndpointAutoConfiguration.java
- spring-cloud-alicloud-acm/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Add spring.cloud.alicloud.acm.enable to ACM module by adding
`@ConditionalOnProperty` annotations on auto-configuration classes and
bootstrap-configuration classes
This PR adds spring.cloud.alicloud.acm.enable to ACM module
Fixes #744 
By adding `@ConditionalOnProperty` annotations to auto-configuration classes and bootstrap-configuration classes
Add `spring.cloud.alicloud.acm.enable=false` to the `bootstrap.properties` of acm-local-example and the example app will throw an exception because `user.id` is not configured.  And updating it on acm server won't help.  Only configuring it locally(in bootstrap.properties) will help. 
NONE
> fix #744 Add spring.cloud.alicloud.acm.enable to ACM module

- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/java/com/alibaba/cloud/examples/ConsumerApplication.java
- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/java/com/alibaba/cloud/examples/UrlCleaner.java
- spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelConstants.java
- spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/annotation/SentinelRestTemplate.java
- spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/BlockClassRegistry.java
- spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelBeanPostProcessor.java
- spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelProtectInterceptor.java
- spring-cloud-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/SentinelRestTemplateTests.java
This PR enables users to configure `UrlCleaner` and `UrlCleanerClass` in `SentinelRestTemplate` annotation to clean the url.
Fixes #762 
Adding two new configurations `UrlCleaner` and `UrlCleanerClass` into `SentinelRestTemplate`
In nacos-discovery-example, there was a useless rule for resource `GET:http://service-provider/echo/{str}`.  Now with the new configurations of `SentinelRestTemplate`, the wildcard `{str}` can be recognized and the rule is fully functioning.
Now I check all three configurations---`block`, `fallback` and `urlCleaner` in `checkBlock4RestTemplate`.  Do we need to consider refactor this function?
> Fix #762 SentinelRestTemplate enhancement

- spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboLoadBalancedRestTemplateAutoConfiguration.java
The restTemplate adapt operation triggered by ApplicationStartedEvent on `DubboLoadBalancedRestTemplateAutoConfiguration`, I think it's too late, often occur the **concurrent modificate exception** due to modify restTemplate Interceptors . the demo project [https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-consumer-sample](https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-consumer-sample) also can verify it,  I found the reason is  `ScheduledAnnotationBeanPostProcessor`  application event run before the Initial adaptation.
run the dubbo demo project
> Advance adapt Dubbo restTemplates

- spring-cloud-alibaba-examples/oss-example/src/main/java/com/alibaba/cloud/examples/OssController.java
- spring-cloud-alicloud-oss/pom.xml
- spring-cloud-alicloud-oss/src/main/java/com/alibaba/alicloud/oss/OssAutoConfiguration.java
- spring-cloud-alicloud-oss/src/main/java/com/alibaba/alicloud/oss/OssConstants.java
- spring-cloud-alicloud-oss/src/main/java/com/alibaba/alicloud/oss/resource/OssStorageProtocolResolver.java
- spring-cloud-alicloud-oss/src/main/java/com/alibaba/alicloud/oss/resource/OssStorageResource.java
- spring-cloud-alicloud-oss/src/test/java/com/alibaba/alicloud/oss/resource/DummyOssClient.java
- spring-cloud-alicloud-oss/src/test/java/com/alibaba/alicloud/oss/resource/OssStorageResourceTest.java
Allow the OssStorageResource to support WritableResource so that we could get an OutputStream and directly upload binary from the resource.
NONE
As the java oss sdk only provide putObject with an InputStream to upload file, we use "Pipe OutputStream and InputStream" to associate the input stream to the output stream to be returned from the method.
We have to use an fixed thread pool to allow async read things from the inputStream, to which the outter outputStream write, as the putObject is sync.
1. Deliberately create mocked unittest cases to verify this.
2. In the examples project, add a sample code to demo the usage.
Please kindly let me know had there be any problem concerning the usage of oss.
> Support OssStorage Resource as WritableResource and add related unittest cases

- spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/DubboServiceMetadataRepository.java
- spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/AbstractSpringCloudRegistry.java
- spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/SpringCloudRegistry.java
- spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/SpringCloudRegistryFactory.java
- spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/service/DubboGenericServiceFactory.java
- fix https://github.com/alibaba/spring-cloud-alibaba/issues/904: resolve a series of problems caused by restarting providers when no provider instances exists.
- resolve the problems that `ServiceRestMetadata` will never be accessible in the case of failed generalization calls.
> Some optimizations about Dubbo Spring Cloud

- spring-cloud-stream-binder-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/properties/RocketMQBinderConfigurationProperties.java
add validation on nameServer
Fixes #977
use `@Validated` add `@Pattern(regexp = "^[\\d.:;]+$")` to verify can only use "0-9", "." , ":" and ";"
use RocketMQAutoConfigurationTests
> add validation on nameServer

- spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/web/SeataHandlerInterceptor.java
- spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/web/SeataHandlerInterceptorConfiguration.java
`com.alibaba.cloud.seata.web.SeataHandlerInterceptor` 和 `com.alibaba.cloud.seata.web.SeataHandlerInterceptorConfiguration` 在web环境下才工作的,但是果然环境仅依赖`spring-boot-starter`的时候就出现异常了或者容器用的不是`servlet`容器的话也是出现问题的,所以我添加了条件判断
> [fix]设置在web环境下才注入拦截器

- spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelBeanPostProcessor.java
Fixes #1156
When someone init a bean with a name of null, the program will end with NullPointerException
Handle the scenario where the registed bean name is null
> Fixes #1156, handle the scenario where the registed bean name is null

- spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelProperties.java
- spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelWebAutoConfiguration.java
Enhance SentinelProperties.Filter support to config CommonFilter WEB_CONTEXT_UNIFY property.
Fixes #1138
1.SentinelProperties.Filter add webContextUnify property,
2.SentinelWebAutoConfiguration sentinelFilter modify: registration.addInitParameter(CommonFilter.HTTP_METHOD_SPECIFY,
String.valueOf(properties.getHttpMethodSpecify()));
registration.addInitParameter(CommonFilter.WEB_CONTEXT_UNIFY,
String.valueOf(filterConfig.isWebContextUnify()));
CommonFilter.init work well
no
> Enhance SentinelProperties Config

- spring-cloud-stream-binder-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/RocketMQBinderUtils.java
- spring-cloud-stream-binder-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/RocketMQMessageChannelBinder.java
- spring-cloud-stream-binder-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/consuming/RocketMQListenerBindingContainer.java
- spring-cloud-stream-binder-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/integration/RocketMQMessageSource.java
- spring-cloud-stream-binder-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/properties/RocketMQBinderConfigurationProperties.java
- spring-cloud-stream-binder-rocketmq/src/test/java/com/alibaba/cloud/stream/binder/rocketmq/RocketMQAutoConfigurationTests.java
Change the class type of RocketMQ nameServer to `List<String>`
fixed #1054
> Change the class type of RocketMQ nameServer

- spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosWatch.java
There is a problem in module “spring-cloud-alibaba-nacos-discovery”. At first, I thought the problem was caused by Nacos, see the issue of nacos: [https://github.com/alibaba/nacos/issues/1596](https://github.com/alibaba/nacos/issues/1596)，although the application is closed, but the java process is still alive。Later, I found that the problem was caused in the project “spring-cloud-alibaba-nacos-discovery”。
Because the **NacosWatch** bean did not call its close() method when it was destroyed, and did not shtdown the "**taskScheduler**" thread pool object which it created. The other daemon-threads could not be automatically terminated because there was still a user thread, finally graceful shutdown application failed.
NONE
com.alibaba.cloud.nacos.discovery.NacosWatch.java
```
@Override …
```
> shutdown the taskScheduler when the NacosWatch bean is destroyed.

- spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosConfigEndpointAutoConfiguration.java
- spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-config/src/main/resources/META-INF/additional-spring-configuration-metadata.json
add the health check exist in version < 1.5.1, 2.0.0 as an option.
we use the health check for k8s readnessprobe, find out that the new implement in version >= 1.5.1,2.0.0 make the status down because of unstable network, and the deployments restart.
applicaion works fine once get the configs from the nacos server, so i think there should have a switch to close the health check, and add back the old implement as an option with which the status will be up after the applicaion store the configuration in local cache.
> healthcheck switch config property

- spring-cloud-starter-alibaba/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/AbstractSpringCloudRegistry.java
ReStarting a consumer and then starting a provider does not automatically discover the registration
Fixes  https://github.com/alibaba/spring-cloud-alibaba/issues/753
// issue : ReStarting a consumer and then starting a provider does not automatically discover the registration
// Re-obtain the latest list of available metadata address here, ip or port may change.
dubboMetadataConfigServiceProxy.removeProxy(serviceName);
repository.removeMetadataAndInitializedService(serviceName);
dubboGenericServiceFactory.destroy(serviceName);
repository.initializeMetadata(serviceName);
大家好, 我已经提交了改正的代码, 请过目. 已经在公司内部的k8s生产环境实验通过了.
使用随机端口或者k8s应用都可以复现这个问题.
* 解决注册中心推送新IP的时候，dubbo服务一直不替换老IP或端口的BUG。
nacos刷新dubbo客户端对象的逻辑是，先去元数据服务查询接口定义信息， 再用接口信息去重建客户端内部的Invoker对象 {@link Invoker} …
> [fix #753] https://github.com/alibaba/spring-cloud-alibaba/issues/753

- spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/condition/MissingSpringCloudRegistryConfigPropertyCondition.java
- spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/env/DubboNonWebApplicationEnvironmentPostProcessor.java
修复使用dubbo2.7.5错误
Fix use Dubbo 2.7.5 error，#1310
Fixes #1310
MissingSpringCloudRegistryConfigPropertyCondition类以及DubboNonWebApplicationEnvironmentPostProcessor类在获取属性的时候使用了dubbo的工具类org.apache.dubbo.config.spring.util.PropertySourcesUtils.getPrefixedProperties，这个类在2.7.5已经不存在了，可以使用com.alibaba.spring.util.PropertySourcesUtils.getSubProperties代替，如dubbo2.7.5自己使用的那样。
修改后，同时兼容2.7.4.1
Missingspringcloudregistryconfigpropertycondition class and dubbononwebapplicationenvironmentpostprocessor class used Dubbo's tool class org.apache.dubbo.config.spring.util.propertysourcesutils.getprefixedproperties when getting properties. This class no longer exists in 2.7.5. You can use com.alibaba.spring.util.propertysourcesutils.getsubproperties Instead, as Dubbo 2.7.5 uses on its own.
After modification, it is …
> Fix #1310 Compatible with Dubbo 2.7.5

- spring-cloud-alibaba-dependencies/pom.xml
- spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/application.properties
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelProperties.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelWebAutoConfiguration.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/endpoint/SentinelEndpoint.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/endpoint/SentinelHealthIndicator.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/SentinelAutoConfigurationTests.java
- upgrade Sentinel version to 1.7.2
- add a new configuration item `spring.cloud.sentinel.web-context-unify` to specify whether unify web context(i.e. use the default context name), and is `true` by default.
Fixes #1431
> Upgrade Sentinel version to 1.7.2

- spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/SpringCloudRegistryFactory.java
SpringCloudRegistryFactory should inherit AbstractRegistryFactory and cache the registry instance that has been created.
> fix the issue SpringCloudRegistryFactory always create registry instance

- spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/DubboProtocolConfigSupplier.java
**1. If the service provider does not configure dubbo.protocol.port, when the service is exposed, it will select the default port exposure of the corresponding protocol**
```
org.apache.dubbo.config.ServiceConfig#findConfigedPorts
ExtensionLoader.getExtensionLoader(Protocol.class).getExtension(name).getDefaultPort();
if (portToBind == null || portToBind == 0) {
portToBind = defaultPort;
}
```
**2. When the DubbMetadataService is exposed, the port of protocol corresponding to ServiceConfig is - 1. As a result, when the service is exposed, the exposed port will start to obtain the available port from the default port. Because the 20880 has been occupied at this time, the obtained port will be 20881. At the same time, the port registered in the metadata of the registry is 20881**
``` …
```
> Fix dubbo service call error when dubbo.protocol.port is not specified

- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java
我们的场景是在多注册中心不重启实例的情况下动态切换注册中心。
NONE
实例已经在线的情况下，通过post /actuator/env 或由配置中心更改了${spring.cloud.nacos.discovery.server-addr}配置,NacosDiscoveryProperties Bean重载完static NamingService还是保留旧的注册中心地址。导致无法注册到新的注册中心
通过post /actuator/env 或由配置中心更改了 查看注册中心实例是否注册
> 多注册中心动态切换serverAddr配置还是保留旧注册中心地址

- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/endpoint/SentinelHealthIndicator.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/endpoint/SentinelHealthIndicatorTests.java
For sentinel , we just no need remove the pod just because of the dashboard unreachable.
If sentinel dashboard crash , we will remove the pod just because indicator mark down. 
It's bad to do like this. 
https://github.com/alibaba/spring-cloud-alibaba/issues/842 
We mark just UNKNOWN so the healthIndicator will return https status 200.
Killing dashboard , then will return 200 other then 503
> to avoid k8s readinessProbe remove the pod

- spring-cloud-alibaba-examples/seata-example/order-service/pom.xml
示例项目中的 spring-cloud-alibaba-examples=>seata-example=>order-service=>pom.xml中的maven name写错了，写成了
Spring Cloud Starter Alibaba Seata Example - Business Service
猜测应该是复制的时候没有改正，已改为
Spring Cloud Starter Alibaba Seata Example - Order Service
> maven project name change

- spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/application.properties
When call feign API,  the first time always exception by timeout, not control by random seed.
It avoid time out to cause Exception.
Give time buffer to feign client in application.properties
> Timeout exception in feign first time calling

- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme.md
There is an important, yet missing option spring.cloud.nacos.discovery.enabled.
No
I added this option's description by following  the "More configuration items" format.
Ran the nacos example code.
None
> Add one missing configuration item

- spring-cloud-alibaba-examples/rocketmq-example/rocketmq-produce-example/src/main/java/com/alibaba/cloud/examples/RocketMQProduceApplication.java
- spring-cloud-alibaba-examples/sentinel-example/sentinel-zuul-example/src/main/java/com/alibaba/cloud/examples/ZuulConfiguration.java
- spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/ConfigConstants.java
- spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/zuul/SentinelZuulAutoConfiguration.java
- spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/zuul/SentinelZuulProperties.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java
- spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/AbstractSpringCloudRegistry.java
- spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/DubboCloudRegistry.java
不应该使用类实例访问静态成员\不应该直接使用不确定的值调用equals容易空指针\final static应该使用大写命名并且使用下划线
> 不应该使用类实例访问静态成员\不应该直接使用不确定的值调用equals容易空指针\final static应该使用大写命名并且使用下划线

- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigManager.java
- 当程序在weblogic反复多次部署时，会导致metaspace oom.分析原因是因为nacos没有关闭轮训配置的线程池,从而导致weblogic的classloader无法被回收。
- none
- NacosConfigManager增加销毁方法,关闭nacos相关线程池
- 设置metaspace一个相对较小的值,反复部署,观察full GC是否能够卸载掉无用的class
> fix(NacosConfigManager): 修复weblogic中classloader泄漏问题

- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/logging/NacosLoggingListener.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/resources/META-INF/spring.factories
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/logging/NacosLoggingListener.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/resources/META-INF/spring.factories
Listens for `ApplicationEnvironmentPreparedEvent`, reload `nacos-client` log config
Fixes #1931
> [ISSUE-#1931] Add a reset Nacos Log Config listener.

- spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/DubboCloudRegistry.java
Fixes #2031
Receive each service instance tag and replace `dubbo.tag` parameter when clone exported url,
thus consumer can select the same tag invoker and complete the remote invocation correctly!
consumer invoke with set tag_key`RpcContext.getContext().setAttachment(CommonConstants.TAG_KEY, "tag1");`
consumer can not invoke provider services with tag when not set tag  key `RpcContext.getContext().setAttachment(CommonConstants.TAG_KEY, "tag1");`,
but can invoke provider services with tag! I think that's dubbo framework bug if [dubbo documentation](https://dubbo.apache.org/zh/docs/v2.7/user/examples/routing-rule/) is correct!
> bugfix invokers metadata tag error

- spring-cloud-alibaba-examples/rocketmq-example/rocketmq-produce-example/src/main/resources/application.properties
- spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/autoconfigurate/ExtendedBindingHandlerMappingsProviderConfiguration.java
- spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/autoconfigurate/RocketMQBinderAutoConfiguration.java
- spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/resources/META-INF/spring.factories
修复自定义bean无法被rockmq启用的bug
Fixes #2040
把RocketMQConfigBeanPostProcessor的注入方式从spring.binders移动到spring.factories中，
前者经过spring-cloud-stream代理会出现一个新的child context 导致自定义常用bean无法经过RocketMQConfigBeanPostProcessor处理
启动RocketMQProduceApplication事务消息通过TransactionListenerImpl且无错误
> fix issus#2040

- spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/DubboServiceMetadataRepository.java
修复问题：
1. 使用服务分组，当`group`是多个的情况下（例如`group="provider1,provider2"`），获取不到服务提供者
2. 使用分组聚合，当`group`是多个的时候下（`group="provider1,provider2"`）或者为`*`（`group="*"`）的情况下，获取不到服务提供者
修改`com.alibaba.cloud.dubbo.metadata.repository.DubboServiceMetadataRepository#getExportedURLs`判断group为多个或者*的情况
```java
public List<URL> getExportedURLs(String serviceInterface, String group,
String version) {
if (group != null) {
List<URL> urls = new LinkedList<>();
if (CommonConstants.ANY_VALUE.equals(group)) {
String serviceKey = URL.buildKey(serviceInterface, group, version);
String expectKey = serviceKey.substring(2);
for (String key : allExportedURLs.keySet()) {
if (key.endsWith(expectKey)) {
urls.addAll(allExportedURLs.get(key));
}
}
}
else {
String[] groups = group.split(CommonConstants.COMMA_SEPARATOR);
for (String …
```
> 修复dubbo使用服务分组和分组聚合获取不到url

- spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/resources/application.properties
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java
Support for registration of quick failed configuration items `spring.cloud.nacos.discovery.fail-fast`
When the Service register failed
- If `true`, The application start will fail. ( default is `true`)
- If `false`, The application start will success.  When Nacos Server is ready, the service instance is automatically registered.
Fixed #2099 
Fixed #1604
> [Feature] support for registration of quick failed configuration items

- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java
当调用 [NacosServiceRegistry](https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java "NacosServiceRegistry") 的 `getStatus` 方法：
```java
public Object getStatus(Registration registration)
```
获取实例状态时，由于底层获取实例列表的方法是：
```java
public List<Instance> getAllInstances(String serviceName) throws NacosException
```
使用的是默认的分组（`DEFAULT_GROUP`），当实例不在默认分组下时则无法获取到实例列表，最终导致无法获取实例状态
无
将底层获取实例列表的方法改为：
```java
public List<Instance> getAllInstances(String serviceName, String groupName) throws NacosException {
```
调用 `NacosServiceRegistry` 的 `getStatus`  方法即可复现
无
> 修复当实例不在默认分组下时获取不到实例状态的BUG

- spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-client-sample/pom.xml
- spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-client-sample/src/main/resources/bootstrap.yaml
- spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-server-sample/src/main/resources/bootstrap.yaml
- spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/DubboCloudRegistry.java
as https://github.com/alibaba/spring-cloud-alibaba/issues/2007
DubboCloudRegistry should be init earlier. 
---
original DubboCloudRegistry listenerning ContextRefreshedEvent, so only if all spring environment prepared then the DubboCloudRegistry can be init.
but, when creating dubbo service reference, ReferenceConfig need DubboCloudRegistry init finish. 
so. it will lead to the provider not exist exception.
---
在原先的实现中，DubboCloudRegistry 通过监听 ContextRefreshedEvent 事件来实现初始化。所以只有完整的spring环境全部准备弯沉过以后，才会触发 DubboCloudRegistry 的初始化逻辑。
但是由于在创建 dubbo 的 Reference 过程中，需要 DubboCloudRegistry 初始化完成。
这就导致了只要开启了 dubbo 的 consumer.check 就会触发 noprovider 的异常。
> init DubboCloudRegistry when subscribe or unsubscribe

- spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/factorybean/NacosDataSourceFactoryBean.java
when using sentinel + nacos. If nacos is using the MSE version and authentication is enabled.
ak/sk can not sent nacos server correctly.
> support ak/sk authentication when using serverAddr

- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/feign/SentinelFeign.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/feign/SentinelFeignAutoConfiguration.java
- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/feign/SentinelTargeterAspect.java
Using AOP to obtain feignClientFactoryBean, in order to create SentinelInvocationHandler can get it.
fix following issue: 
- https://github.com/alibaba/spring-cloud-alibaba/issues/2137
- https://github.com/alibaba/spring-cloud-alibaba/issues/2122
- https://github.com/alibaba/spring-cloud-alibaba/issues/2107
> use aop to save and get FeignClientFactoryBean

- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelProtectInterceptor.java
Throw exception directly when exception is not an BlockException. 
Because Sentinel can't do anything if the exception is not an BlockException, the exception should be handled upstream.
fix issue :
- Closes #2044
- Closes #1346
> throw exception directly when exception is not an BlockException

- spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/integration/inbound/RocketMQConsumerFactory.java
- spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/integration/outbound/RocketMQProduceFactory.java
- spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/properties/RocketMQCommonProperties.java
- spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/utils/RocketMQUtils.java
同一应用连接多个集群时，因无法设置unitName导致MQClientInstance只有一个生效
配置添加unitName，创建producer和consumer时进行设置
> feat: 配置添加unitName，支持同一应用连接多个集群

- spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosWatch.java
Fixes #2253: ThreadPoolTaskScheduler instance in NacosWatch can't be shutdown, causing JVM process leak.
Fixes #2253
Implements `DisposableBean` BeanFactory interface's `destroy` hook method for `NacosWatch` class, calling the existing `stop` method for `org.springframework.context.Lifecycle` interface.
As following code shows:
```java
@Override
public void destroy() {
this.stop();
}
```
1. The port 8081 in used in current host.
2. Start a SpringBoot web application integrated with `spring-cloud-starter-alibaba-nacos-discovery` on port 8081 too.
3. A `org.springframework.boot.web.server.PortInUseException: Port 8081 is already in use` exception would be thrown by `org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle#start` method.
4. When BeanFactory starts destroying, …
> Fixes #2253: ThreadPoolTaskScheduler instance in NacosWatch can't be shutdown.
