alibaba/spring-cloud-alibaba

spring-cloud-alibaba-examples/sentinel-example/readme-zh.md

- Fix the incorrect content about Sentinel annotation example
- Some refinements and updates

Update document for Sentinel examples

---

spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceBuilder.java

Fixes #32 support fileExtension yaml and yml

---

spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/registry/NacosRegistration.java

add management info to registry metadata, Fixes #41

---

spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryClient.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryClientAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/endpoint/NacosDiscoveryEndpoint.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/endpoint/NacosDiscoveryEndpointAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/registry/NacosRegistration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/ribbon/NacosServerList.java
spring-cloud-alibaba-nacos-discovery/src/test/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryAutoConfigurationTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/org/springframework/cloud/alibaba/nacos/ribbon/NacosRibbonClientConfigurationTests.java

separate registry and discovery

separate registry and discovery, Fixes #42

---

spring-cloud-alicloud-acm/src/main/java/org/springframework/cloud/alicloud/acm/AcmAutoConfiguration.java
spring-cloud-alicloud-acm/src/main/java/org/springframework/cloud/alicloud/acm/refresh/AcmContextRefresher.java
spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/acm/AcmIntegrationProperties.java

#	spring-cloud-alicloud-acm/src/main/java/org/springframework/cloud/alicloud/acm/refresh/AcmContextRefresher.java

Extract acm configuration to bootstrap phase.

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/acm.adoc

添加acm reference文档

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc

添加Nacos的config文档

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc

更改Nacos的拼写错误

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-discovery.adoc

添加Nacos Discovery 的reference 文档

添加Nacos Discovery 的reference 文档

---

README-zh.md
README.md
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-discovery.adoc

添加 Nacos Discovery 到 Reference 目录列表

添加 Nacos Discovery 到 Reference 目录列表

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc

修正Nacos Config 文档

---

pom.xml
spring-cloud-alibaba-examples/rocketmq-example/pom.xml
spring-cloud-alibaba-examples/rocketmq-example/readme-zh.md
spring-cloud-alibaba-examples/rocketmq-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/Foo.java
spring-cloud-alibaba-examples/rocketmq-example/src/main/resources/application.properties
spring-cloud-stream-binder-rocketmq/pom.xml
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/RocketMQBinderConstants.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/RocketMQMessageChannelBinder.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/actuator/RocketMQBinderEndpoint.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/actuator/RocketMQBinderHealthIndicator.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/config/RocketMQBinderAutoConfiguration.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/config/RocketMQBinderEndpointAutoConfiguration.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/consuming/ConsumersManager.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/integration/RocketMQInboundChannelAdapter.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/integration/RocketMQMessageHandler.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/metrics/ConsumerGroupInstrumentation.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/metrics/ConsumerInstrumentation.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/metrics/InstrumentationManager.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/metrics/ProducerInstrumentation.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/properties/RocketMQBinderConfigurationProperties.java

refactor includes:
1. make `metrics-core` module as provided
2. magic value
3. some bad logic

Refactor binder and update examples

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc

订正 Nacos Config 的 reference 文档。
1、订正一些不太正确的词
2、将 spring.profile.actives 的配置突出说明是放在 bootstrap.properties 文件中
3、其他的语句上的订正

订正 Nacos Config 的 reference 文档

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-docs/src/main/asciidoc-zh/sentinel.adoc
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/ConsumerApplication.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/TestController.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/resources/flowrule.json
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/ProviderApplication.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/ServiceApplication.java
spring-cloud-alibaba-sentinel-datasource/pom.xml
spring-cloud-alibaba-sentinel-datasource/src/main/java/org/springframework/cloud/alibaba/sentinel/datasource/converter/JsonConverter.java
spring-cloud-alibaba-sentinel-datasource/src/main/java/org/springframework/cloud/alibaba/sentinel/datasource/converter/XmlConverter.java
spring-cloud-alibaba-sentinel/pom.xml
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/SentinelProperties.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/annotation/SentinelRestTemplate.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelAutoConfiguration.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelBeanPostProcessor.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelProtectInterceptor.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/endpoint/SentinelEndpoint.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/feign/SentinelContractHolder.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/feign/SentinelFeign.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/feign/SentinelFeignAutoConfiguration.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/feign/SentinelInvocationHandler.java
spring-cloud-alibaba-sentinel/src/main/resources/META-INF/additional-spring-configuration-metadata.json
spring-cloud-alibaba-sentinel/src/main/resources/META-INF/spring.factories
spring-cloud-alibaba-sentinel/src/test/java/org/springframework/cloud/alibaba/sentinel/SentinelAutoConfigurationTests.java

issues:
1. sentinel integration with feign #6 
3. rename @SentinelProtect to @SentinelRestTemplate #9 
3. support parameter flow control #115 
examples:
1. update nacos discovery example with sentinel feign
others:
1. add log configuration for Sentinel

Sentinel integration with feign and handle some issues

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc

add a new feature content of that support custom Data Id for Nacos Config

 add a new feature content of that support custom Data Id for Nacos Config

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/pom.xml
spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/pom.xml
spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/rocketmq/RocketMQBusApplication.java
spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/rocketmq/User.java
spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/rocketmq/UserRemoteApplicationEvent.java
spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/src/main/resources/bootstrap.properties
spring-cloud-starter-alibaba/pom.xml
spring-cloud-starter-alibaba/spring-cloud-starter-bus-rocketmq/pom.xml
spring-cloud-starter-alibaba/spring-cloud-starter-bus-rocketmq/src/main/java/org/springframework/cloud/bus/rocketmq/env/RocketMQBusEnvironmentPostProcessor.java
spring-cloud-starter-alibaba/spring-cloud-starter-bus-rocketmq/src/main/resources/META-INF/spring.factories

add module spring cloud bus rocketmq, close #119

add spring cloud bus rocketmq for 1.x

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-docs/src/main/asciidoc-zh/sentinel.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/sentinel.adoc
spring-cloud-alibaba-sentinel/pom.xml
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/rest/SentinelClientHttpResponse.java

sentinel support custom block response by sentinelClientHttpResponse

sentinel support custom block response by sentinelClientHttpResponse

---

spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigBootstrapConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosPropertySourceRepository.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceBuilder.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceLocator.java

1、更改获取所有NacosPropertySource的方式

更改获取所有NacosPropertySource的方式

---

spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigBootstrapConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosPropertySourceRepository.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceBuilder.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceLocator.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/refresh/NacosContextRefresher.java

更改Nacos Config 获取NacosPropertiesSource 列表的方式

change the style for get the list of NacosPropertiesSource

---

spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigBootstrapConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigProperties.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosPropertySourceRepository.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceBuilder.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceLocator.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/endpoint/NacosConfigEndpoint.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/endpoint/NacosConfigEndpointAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/endpoint/NacosConfigHealthIndicator.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/refresh/NacosContextRefresher.java
spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/nacos/NacosParameterInitListener.java

Prevent non-refreshing configurations from retrieving the latest configuration values when refreshing

Prevent non-refreshing

---

spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceLocator.java

Fix Incorrect letter 

---

spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryClient.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryClientAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/endpoint/NacosDiscoveryEndpoint.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/endpoint/NacosDiscoveryEndpointAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/registry/NacosAutoServiceRegistration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/registry/NacosRegistration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/ribbon/NacosRibbonClientConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/ribbon/NacosServerList.java
spring-cloud-alibaba-nacos-discovery/src/test/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryAutoConfigurationTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/org/springframework/cloud/alibaba/nacos/ribbon/NacosRibbonClientConfigurationTests.java

[Why field injection is evil](http://olivergierke.de/2013/11/why-field-injection-is-evil)
-  unsafe code
- more complicated to test
according to this, use constructor injection instead of field injection

use constructor injection instead of field injection

---

.travis.yml
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceLocator.java

add .travis.yml for ci

---

.circleci/config.yml
.codecov.yml
pom.xml
spring-cloud-alibaba-dependencies/pom.xml

add Codecov for project

---

.circleci/config.yml
.codecov.yml
pom.xml

reduce the time of ci build and test

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/sms.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/spring-cloud-alibaba.adoc
spring-cloud-alibaba-examples/sms-example/readme-zh.md

sms document for reference document and readme for example

sms document

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-docs/pom.xml
spring-cloud-alibaba-examples/acm-example/acm-local-example/pom.xml
spring-cloud-alibaba-examples/ans-example/ans-consumer-feign-example/pom.xml
spring-cloud-alibaba-examples/ans-example/ans-consumer-ribbon-example/pom.xml
spring-cloud-alibaba-examples/ans-example/ans-provider-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-config-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/pom.xml
spring-cloud-alibaba-examples/oss-example/pom.xml
spring-cloud-alibaba-examples/pom.xml
spring-cloud-alibaba-examples/rocketmq-example/pom.xml
spring-cloud-alibaba-examples/schedulerx-example/schedulerx-simple-task-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/sentinel-dubbo-api/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/sentinel-dubbo-consumer-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/sentinel-dubbo-provider-example/pom.xml
spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/pom.xml
spring-cloud-alibaba-nacos-discovery/pom.xml
spring-cloud-starter-alibaba/pom.xml
spring-cloud-starter-alicloud/pom.xml

update cobertura settings for reduce build time

update cobertura settings for reduce build time

---

spring-cloud-alicloud-ans/src/main/java/org/springframework/cloud/alicloud/ans/registry/AnsRegistration.java

remove set port action in AnsRegistration

remove set port action in AnsRegistration

---

pom.xml
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/endpoint/SentinelEndpoint.java

1.update cobertura settings
2.fix endpoint's degradeRules return value

update cobertura settings

---

spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-discovery-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-discovery-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/GatewayApplication.java
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-discovery-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-provider-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-provider-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/ProviderApplication.java
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-provider-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/readme-zh.md
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/readme.md
spring-cloud-alibaba-sentinel/pom.xml
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelCircuitBreakerConfiguration.java
spring-cloud-alibaba-sentinel/src/main/resources/META-INF/spring.factories

This is done to solve the problem of using standard Spring Cloud annotations.
1 . import spring-cloud-commons
2. new blank Configuration SentinelCircuitBreakerConfiguration
3. set up spring.factories EnableCircuitBreaker
As the isuue say,@EnableCircuitBreaker annotation doesn't really do anything, it's just an identifier.

fix #294  #274 EnableCircuitBreaker error & add nacos gateway example

---

spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryProperties.java

fixed netInterface NullPointerException

---

spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/ans/AnsProperties.java

 Polish java doc.

---

spring-cloud-alicloud-acm/src/main/java/org/springframework/cloud/alicloud/acm/endpoint/AcmEndpointAutoConfiguration.java
spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/ans/AnsProperties.java
spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/nacos/NacosParameterInitListener.java
spring-cloud-alicloud-oss/src/main/java/org/springframework/cloud/alicloud/oss/resource/OssStorageProtocolResolver.java
spring-cloud-alicloud-schedulerx/pom.xml

Fix code format error and polish java doc.

  Fix code format error and polish java doc.

---

spring-cloud-alicloud-ans/src/test/java/org/springframework/cloud/alicloud/ans/registry/AnsAutoServiceRegistrationIpNetworkInterfaceTests.java

Fixes #331

---

.circleci/config.yml
pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-docs/pom.xml
spring-cloud-alibaba-examples/acm-example/acm-local-example/pom.xml
spring-cloud-alibaba-examples/ans-example/ans-consumer-feign-example/pom.xml
spring-cloud-alibaba-examples/ans-example/ans-consumer-ribbon-example/pom.xml
spring-cloud-alibaba-examples/ans-example/ans-provider-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-config-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-discovery-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-provider-example/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/pom.xml
spring-cloud-alibaba-examples/oss-example/pom.xml
spring-cloud-alibaba-examples/pom.xml
spring-cloud-alibaba-examples/rocketmq-example/pom.xml
spring-cloud-alibaba-examples/schedulerx-example/schedulerx-simple-task-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/sentinel-dubbo-api/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/sentinel-dubbo-consumer-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/sentinel-dubbo-provider-example/pom.xml
spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/pom.xml
spring-cloud-alibaba-nacos-discovery/pom.xml
spring-cloud-alibaba-sentinel-datasource/src/test/java/org/springframework/cloud/alibaba/sentinel/datasource/DataSourcePropertiesConfigurationTests.java
spring-cloud-starter-alibaba/pom.xml
spring-cloud-starter-alicloud/pom.xml

1. replace cobertura to jacoco for support java8 syntax
2. reduce build time less than 6 min
see circleCI build and codecov info
@fangjian0423 @flystar32

replace cobertura to jacoco

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-docs/src/main/asciidoc-zh/sentinel.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/sentinel.adoc
spring-cloud-alibaba-sentinel-datasource/src/main/java/org/springframework/cloud/alibaba/sentinel/datasource/converter/SentinelConverter.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/SentinelWebAutoConfiguration.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelBeanPostProcessor.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelDataSourceHandler.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelProtectInterceptor.java

upgrade sentinel to 1.4.2 & refactor logger -> log & update docs

upgrade sentinel version & update docs & refactor log

---

spring-cloud-alibaba-examples/schedulerx-example/schedulerx-simple-task-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/HelloController.java
spring-cloud-alibaba-examples/schedulerx-example/schedulerx-simple-task-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/TestController.java
spring-cloud-alibaba-examples/schedulerx-example/schedulerx-simple-task-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/TestService.java
spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/nacos/NacosDiscoveryParameterInitListener.java
spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/oss/OssProperties.java
spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/scx/ScxProperties.java
spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/statistics/StatisticsTaskStarter.java
spring-cloud-alicloud-context/src/test/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryAutoConfiguration.java
spring-cloud-alicloud-context/src/test/java/org/springframework/cloud/alicloud/context/nacos/NacosDiscoveryParameterInitListenerTests.java

Add statistics for nacos discovery and test case

 Add statistics for nacos discovery and test case

---

spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/ProviderApplication.java

add @EnableDiscoveryClient in example

use EnableDiscoveryClient

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/pom.xml
spring-cloud-alicloud-sms/pom.xml

1, deleted duplicate properties
2, removed duplicate dependency
3, including the sms-example module

optimized spring-cloud-alicloud-sms pom.xml

---

pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/resources/bootstrap.properties
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosDiscoveryClient.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/endpoint/NacosDiscoveryEndpoint.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/registry/NacosAutoServiceRegistration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/registry/NacosServiceRegistry.java
spring-cloud-alicloud-ans/src/main/java/org/springframework/cloud/alicloud/ans/registry/AnsServiceRegistry.java

1. format code such as logger
2. fixed example's bug
Fixes #392

format code and fixed example's bug

---

spring-cloud-alibaba-coverage/pom.xml

remove the nacos-config-server dependency in coverage module 
@flystar32 @fangjian0423

there is no need calculate nacos-config-server module

---

spring-cloud-alibaba-coverage/pom.xml

it's hard to add unit test in sms,oss,schedulerx modules so i remove them in coverage
@flystar32 @fangjian0423

remove sms,schedulerx,oss modules in coverage

---

pom.xml
spring-cloud-alibaba-docs/src/main/asciidoc-zh/acm.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/ans.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/dependency-management.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-discovery.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/oss.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/schedulerx.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/sms.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/acm.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/ans.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/dependency-management.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/nacos-config.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/nacos-discovery.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/schedulerx.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/sms.adoc
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-discovery-example/pom.xml

Update docs & add spring cloud gateway bom

---

README.md

Removes unnecessary words
NONE

Make concise

---

spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigProperties.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceLocator.java
spring-cloud-alibaba-nacos-config/src/test/java/org/springframework/cloud/alibaba/nacos/NacosConfigurationTests.java

delete useless active profiles in NacosConfigProperties
delete field , getter, setter , toString, and update NacosPropertySourceLocator
Run testcase

Fixes #404

---

spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigBootstrapConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigProperties.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/endpoint/NacosConfigEndpointAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/resources/META-INF/additional-spring-configuration-metadata.json
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosDiscoveryClientAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/resources/META-INF/additional-spring-configuration-metadata.json

support `spring.cloud.nacos.discovery.enabled` and `spring.cloud.nacos.config.enabled`
Fixes #411

support switch Nacos  Discovery/Config enabled

---

spring-cloud-alibaba-examples/fescar-example/account-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/fescar-example/account-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/fescar-example/business-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/fescar-example/business-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/fescar-example/order-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/fescar-example/order-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/fescar-example/storage-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/fescar-example/storage-service/src/main/resources/registry.conf

when fescar upgrade 0.2.0+ configuration file changed
fix #417 when fescar upgrade 0.2.0+ configuration file changed

fix #417 when fescar upgrade 0.2.0+ configuration file changed

---

spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/registry/NacosRegistration.java

add management.endpoints.web.base-path to metadata

add management.endpoints.web.base-path to metadata

---

spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelAutoConfiguration.java
spring-cloud-alibaba-sentinel/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Add "resttemplate.sentinel.enabled" property to enable/disable @SentinelRestTemplate

---

spring-cloud-alibaba-examples/fescar-example/readme-zh.md

update Fescar-Sample readme, undo_log table  unique index instead of normal index
fix #432 update Fescar-Sample readme，unique index instead of normal index

fix #432 update Fescar-Sample readme，unique index instead of normal index

---

spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/rocketmq/RocketMQBusApplication.java
spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/rocketmq/UserRemoteApplicationEvent.java
spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/src/main/resources/bootstrap.properties
spring-cloud-starter-alibaba/spring-cloud-starter-bus-rocketmq/src/main/java/org/springframework/cloud/bus/rocketmq/env/RocketMQBusEnvironmentPostProcessor.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/RocketMQMessageChannelBinder.java

As titled.
None.
1. Using topic when producer group not setting.
2. Adding broadcasting for spring cloud bus topic consumer

Fix bug 4 spring-cloud-starter-bus-rocketmq

---

.codecov.yml
.travis.yml

disable codecov/patch coverage
@fangjian0423 @flystar32

disable codecov/patch coverage

---

spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme-zh.md

Wrong character changes. ‘流量器’==> '浏览器‘

Wrong character changes

---

spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/flowrule.json
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelProtectInterceptor.java
spring-cloud-alibaba-sentinel/src/test/java/org/springframework/cloud/alibaba/sentinel/SentinelAutoConfigurationTests.java

As titled.
close https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/445.

add 'HTTPMethod:' prefix for the resource of using @SentinelRestTemplate

---

.codecov.yml

There is no need compare the overall project coverage and compares it against the base of the pull request 
@flystar32 @fangjian0423

Disable a status for codecov

---

spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/autoconfigure/DubboMetadataAutoConfiguration.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/autoconfigure/DubboMetadataEventHandlingAutoConfiguration.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/metadata/DubboProtocolConfigSupplier.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/registry/netflix/eureka/EurekaRegistrationFactory.java

- #473 : Dubbo Spring Cloud duplicated registration
-  #474 : Dubbo Spring Cloud service consume failed in Eureka

[Bugfix] Dubbo Spring Cloud 

---

spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/scripts/error.sh
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/scripts/feign-error.sh
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/scripts/index.sh
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/scripts/sleep.sh
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/ConsumerApplication.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/TestController.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/resources/degraderule.json
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/ProviderApplication.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelBeanPostProcessor.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelProtectInterceptor.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/feign/SentinelInvocationHandler.java
spring-cloud-alibaba-sentinel/src/test/java/org/springframework/cloud/alibaba/sentinel/SentinelAutoConfigurationTests.java

Optimize CircuitBreaker in RestTemplate & update examples

---

spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosConfigProperties.java
spring-cloud-alibaba-nacos-config/src/test/java/org/springframework/cloud/alibaba/nacos/NacosConfigurationTests.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/discovery/NacosDiscoveryClientAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/resources/META-INF/additional-spring-configuration-metadata.json
spring-cloud-alibaba-nacos-discovery/src/test/java/org/springframework/cloud/alibaba/nacos/registry/NacosAutoServiceRegistrationTests.java

Add switch for Nacos Discovery NacosWatch
Add endpoint port configuration for Nacos
Fixes #496 and  #497
see diff for detail
All testcase has passed and run nacos discovery example to verify it.
None

Fixes #496 and  #497

---

spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/Application.java

1. add an example that reacting to the change of config data using Listener.
2. update string format of output.
3. add default value for _user.age_, to avoid crash if Nacos server is not running.

Add an usage for config listener. We can react to the change of config data.

---

spring-cloud-alibaba-dubbo/pom.xml
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/autoconfigure/DubboServiceAutoConfiguration.java
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-servlet-gateway-sample/src/main/java/org/springframework/cloud/alibaba/dubbo/gateway/DubboGatewayServlet.java

Dubbo Spring Boot Starter 2.7.1

Update Dubbo Spring Boot Starter 2.7.1

---

spring-cloud-alibaba-dubbo/pom.xml
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/actuate/DubboMetadataEndpointAutoConfiguration.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/actuate/endpoint/DubboRestMetadataEndpoint.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/autoconfigure/DubboMetadataAutoConfiguration.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/metadata/repository/DubboServiceMetadataRepository.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/service/DubboMetadataService.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/service/DubboMetadataServiceExporter.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/service/DubboMetadataServiceInvocationHandler.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/service/DubboMetadataServiceProxy.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/service/PublishingDubboMetadataService.java
spring-cloud-alibaba-dubbo/src/main/resources/META-INF/dubbo/default/actuator-endpoints.properties
spring-cloud-alibaba-dubbo/src/main/resources/META-INF/spring.factories
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-web-sample/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-web-sample/src/main/resources/application.yaml

- #538 : Add Production-Ready features for Dubbo Spring Cloud
- #542 : Rename DubboMetadataConfigService to DubboMetadataService
- #543 : DubboMetadataService will be always exported

Dubbo Spring Cloud Updates

---

spring-cloud-alibaba-coverage/pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/seata-example/account-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/account-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/order-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/order-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/resources/registry.conf

upgrade seata dependency and config

upgrade seata dependency and config

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/seata-example/account-service/src/main/java/org/springframework/cloud/alibaba/cloud/examples/AccountController.java
spring-cloud-alibaba-examples/seata-example/account-service/src/main/java/org/springframework/cloud/alibaba/cloud/examples/DatabaseConfiguration.java
spring-cloud-alibaba-examples/seata-example/business-service/src/main/java/org/springframework/cloud/alibaba/cloud/examples/HomeController.java
spring-cloud-alibaba-examples/seata-example/order-service/src/main/java/org/springframework/cloud/alibaba/cloud/examples/DatabaseConfiguration.java
spring-cloud-alibaba-examples/seata-example/order-service/src/main/java/org/springframework/cloud/alibaba/cloud/examples/OrderController.java
spring-cloud-alibaba-examples/seata-example/readme-zh.md
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/java/org/springframework/cloud/alibaba/cloud/examples/DatabaseConfiguration.java
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/java/org/springframework/cloud/alibaba/cloud/examples/StorageController.java
spring-cloud-alibaba-seata/pom.xml
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/GlobalTransactionAutoConfiguration.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/feign/SeataFeignClient.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/feign/SeataFeignClientAutoConfiguration.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/feign/hystrix/SeataHystrixAutoConfiguration.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/feign/hystrix/SeataHystrixConcurrencyStrategy.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/rest/SeataRestTemplateAutoConfiguration.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/rest/SeataRestTemplateInterceptor.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/web/SeataHandlerInterceptor.java

Signed-off-by: jimin.jm <jimin.jm@alibaba-inc.com>
upgrade Seata version to 0.5.0
fix #578

upgrade Seata version to 0.5.0

---

spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-consumer-sample/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-sample/pom.xml

Update the dependencies for bugfix

---

spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-client-sample/src/main/resources/bootstrap.yaml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-consumer-sample/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-sample/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-web-sample/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-server-sample/src/main/resources/bootstrap.yaml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-servlet-gateway-sample/pom.xml

Update  Dubbo Spring Cloud Samples

[Update] Dubbo Spring Cloud Samples

---

spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/autoconfigure/DubboServiceRegistrationAutoConfiguration.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/autoconfigure/condition/MissingSpringCloudRegistryConfigPropertyCondition.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/registry/SpringCloudRegistryFactory.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/service/DubboGenericServiceFactory.java

Dubbo Spring Cloud removes spring-cloud://localhost property

Polish spring-cloud-incubator/spring-cloud-alibaba/#592

---

spring-cloud-alibaba-examples/rocketmq-example/rocketmq-consume-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/RocketMQConsumerApplication.java
spring-cloud-alibaba-examples/rocketmq-example/rocketmq-consume-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/rocketmq-example/rocketmq-produce-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/RocketMQProduceApplication.java
spring-cloud-alibaba-examples/rocketmq-example/rocketmq-produce-example/src/main/resources/application.properties
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/RocketMQMessageChannelBinder.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/consuming/RocketMQMessageQueueChooser.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/integration/RocketMQMessageSource.java
spring-cloud-stream-binder-rocketmq/src/main/java/org/springframework/cloud/stream/binder/rocketmq/properties/RocketMQConsumerProperties.java

close #541.
RocketMQ provide `DefaultMQPullConsumer` to pull msg from broker and integration with `MessageSource` in spring integration.

[RocketMQ Binder] Support PolledConsumer

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/flowrule.json
spring-cloud-alibaba-examples/sentinel-example/sentinel-webflux-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-webflux-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/MyConfiguration.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-webflux-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/SentinelWebFluxApplication.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-webflux-example/src/main/java/org/springframework/cloud/alibaba/cloud/examples/SentinelWebFluxController.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-webflux-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/sentinel-example/sentinel-webflux-example/src/main/resources/flowrule.json
spring-cloud-alibaba-sentinel-zuul/src/main/java/org/springframework/cloud/alibaba/sentinel/zuul/SentinelZuulAutoConfiguration.java
spring-cloud-alibaba-sentinel-zuul/src/main/java/org/springframework/cloud/alibaba/sentinel/zuul/handler/FallBackProviderHandler.java
spring-cloud-alibaba-sentinel/pom.xml
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/SentinelWebAutoConfiguration.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/SentinelWebFluxAutoConfiguration.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/custom/SentinelAutoConfiguration.java
spring-cloud-alibaba-sentinel/src/main/resources/META-INF/spring.factories

#614 
add `sentinel-spring-webflux-adapter` dependency and construct some classes.

[Sentinel] Support Webflux

---

spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/feign/SentinelInvocationHandler.java
spring-cloud-alibaba-sentinel/src/test/java/org/springframework/cloud/alibaba/sentinel/SentinelFeignTests.java

Polish spring-cloud-incubator/spring-cloud-alibaba/#626

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/order-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/order-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/readme-zh.md
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/resources/registry.conf

Signed-off-by: jimin.jm <jimin.jm@alibaba-inc.com>
upgrade Seata version to 0.5.1

upgrade Seata version to 0.5.1

---

spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/http/DefaultHttpRequest.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/http/MutableHttpServerRequest.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/metadata/DubboRestServiceMetadata.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/metadata/DubboTransportedMethodMetadata.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/metadata/MethodMetadata.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/metadata/MethodParameterMetadata.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/metadata/RequestMetadata.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/metadata/RestMethodMetadata.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/metadata/ServiceRestMetadata.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/registry/AbstractSpringCloudRegistry.java
spring-cloud-alibaba-dubbo/src/main/java/org/springframework/cloud/alibaba/dubbo/service/DubboGenericServiceFactory.java
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-servlet-gateway-sample/src/main/java/org/springframework/cloud/alibaba/dubbo/gateway/DubboGatewayServlet.java
spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/NacosPropertySourceRepository.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/feign/SentinelContractHolder.java
spring-cloud-alibaba-sentinel/src/main/java/org/springframework/cloud/alibaba/sentinel/feign/SentinelInvocationHandler.java
spring-cloud-alicloud-context/src/main/java/org/springframework/cloud/alicloud/context/sms/SmsProperties.java
spring-cloud-alicloud-sms/src/main/java/org/springframework/cloud/alicloud/sms/SmsInitializerEventListener.java
spring-cloud-alicloud-sms/src/main/java/org/springframework/cloud/alicloud/sms/base/DefaultAlicomMessagePuller.java
spring-cloud-alicloud-sms/src/main/java/org/springframework/cloud/alicloud/sms/base/QueryTokenForMnsQueueRequest.java
spring-cloud-alicloud-sms/src/main/java/org/springframework/cloud/alicloud/sms/base/QueryTokenForMnsQueueResponse.java
spring-cloud-alicloud-sms/src/main/java/org/springframework/cloud/alicloud/sms/base/TokenGetterForAlicom.java

optimize code to match p3c check rules

optimize code to match p3c check rules

---

spring-cloud-alibaba-dependencies/pom.xml

change dubbo-registry-nacos's groupId to org.apache.dubbo

change dubbo-registry-nacos's groupId to org.apache.dubbo

---

spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryAutoConfiguration.java

remove useless imports

---

README-zh.md
README.md

chore spring cloud alibaba home page maven dependecy version please update to lastest release

---

README-zh.md
README.md
Roadmap-zh.md
Roadmap.md
spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/readme-zh.md
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/README_CN.md

Dubbo graduated from Apache, remove the incubating word  in README.

Dubbo graduated from Apache, remove the incubating word  in README.

---

spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/feign/SeataFeignClient.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/feign/SeataFeignClientAutoConfiguration.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/feign/SeataFeignContext.java
spring-cloud-alibaba-seata/src/main/java/org/springframework/cloud/alibaba/seata/feign/SeataLoadBalancerFeignClient.java

add seata context pass on in SeataLoadBalancerFeignClient

fix loadbalance feignclient seata info

---

spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/ribbon/NacosRibbonClientConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/ribbon/NacosServerIntrospector.java

fix #634 , add nacos server introspector 
#634 
add nacos server introspector

fix #634 , add nacos server introspector 

---

README-zh.md

update description with Spring Cloud and Spring Boot version info

update description with version

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-dubbo/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/pom.xml

as titled.
upgrade spring cloud version to greenwich.sr2.
s-c-commons, s-c-netflix, s-c-openfeign, s-c-bus, s-c-gateway upgrade from 2.1.1.RELEASE to 2.1.2.RELEASE .

Updates to spring cloud Greenwich.SR2

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-dubbo/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/pom.xml

as titled.
upgrade spring cloud version to finchley.sr4.
s-c-commons, s-c-netflix, s-c-openfeign, s-c-bus, s-c-gateway upgrade from 2.0.3.RELEASE to 2.0.4.RELEASE .

Updates to spring cloud Finchley.SR4

---

spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-nacos-discovery/src/main/java/org/springframework/cloud/alibaba/nacos/registry/NacosServiceRegistry.java

add modify Nacos instance status support
#728
Implements ServiceRegistry's getStatus and setStatus method.

add modify Nacos instance status support

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/seata-example/account-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/account-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/order-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/order-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/readme-zh.md
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/resources/registry.conf
spring-cloud-alibaba-seata/pom.xml

Signed-off-by: slievrly <slievrly@163.com>
upgrade seata to 0.7.1 and update seata sample
`git cherry-pick 5e7dd20e4a29d65fe59712ee56a74fd0f00fd6c9`

upgrade seata to 0.7.1 and update seata sample

---

README-zh.md
README.md
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-servlet-gateway-sample/pom.xml

Fix the sample compile error
yes
ci success

Fix the sample compile error

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-spring-cloud-gateway-example/src/main/resources/application.yaml
spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/ConfigConstants.java
spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/scg/SentinelGatewayProperties.java
spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/scg/SentinelSCGAutoConfiguration.java

[Sentinel] Upgrade Sentinel 1.6.3

---

spring-cloud-alibaba-examples/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/readme-zh.md
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/readme.md
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/java/com/alibaba/cloud/examples/ConsumerApplication.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/java/com/alibaba/cloud/examples/controller/TestController.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/java/com/alibaba/cloud/examples/fallback/EchoServiceFallback.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/java/com/alibaba/cloud/examples/fallback/EchoServiceFallbackFactory.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/java/com/alibaba/cloud/examples/service/EchoService.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/resources/application.yml
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-provider-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-provider-example/src/main/java/com/alibaba/cloud/examples/ProviderApplication.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-provider-example/src/main/java/com/alibaba/cloud/examples/controller/EchoController.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-provider-example/src/main/resources/application.yml

When I wanted to use feign to integrate sentinel calls, I found that there was no documentation on how to use the sentinel and how to use it. So I would like to share this simple example
no
Add two modules in the example directory
Follow readme.md  to launch both services

add sentinel feign example and doc

---

spring-cloud-alibaba-examples/seata-example/account-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/order-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/resources/file.conf
spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/GlobalTransactionAutoConfiguration.java
spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/SeataProperties.java
spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/feign/SeataFeignClient.java
spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/feign/SeataLoadBalancerFeignClient.java

fescar -> seata

---

spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigProperties.java

Modify NacosConfigProperties enableRemoteSyncConfig field annotation

Modify NacosConfigProperties enableRemoteSyncConfig field annotation

---

spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/DubboServiceMetadataRepository.java
spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/AbstractSpringCloudRegistry.java
spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/service/DubboMetadataServiceProxy.java

Fix dubbo spring cloud dynamic service discovery. refer these issues: 
https://github.com/alibaba/spring-cloud-alibaba/issues/753, https://github.com/alibaba/spring-cloud-alibaba/issues/770, https://github.com/alibaba/spring-cloud-alibaba/issues/695
@mercyblitz pls review it.

Dubbo spring cloud dynamic service discovery

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-discovery.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/nacos-discovery.adoc

Fix nacos doc typo. refer these issues:
#244

Fix nacos doc typo

---

spring-cloud-stream-binder-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/RocketMQBinderConstants.java
spring-cloud-stream-binder-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/consuming/RocketMQListenerBindingContainer.java

消费者需要利用重试次数做一些自定义动作
在转换成Spring Message消息前，添加到Rocketmq消息头中
获取在消费者com.alibaba.cloud.stream.binder.rocketmq.RocketMQBinderConstants#ROCKETMQ_RECONSUME_TIMES消息头

add reconsume times header

---

spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/feign/SentinelFeign.java
spring-cloud-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/ContextIdSentinelFeignTests.java

fix spring cloud open feign in g version , sentinel-feign contextid bug
Fixes https://github.com/alibaba/spring-cloud-alibaba/issues/793

fix spring cloud open feign in g version , sentinel-feign contextid bug

---

spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosPropertySourceRepository.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceBuilder.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosServerList.java

Optimizing and reusing code

---

spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md
spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme.md

some doc no error correction
fix some doc error.

some doc no error correction

---

spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/GatewayEnvironmentPostProcessor.java
spring-cloud-alibaba-sentinel-gateway/src/main/resources/META-INF/spring.factories

The web filters should be disabled if current application is an API gateway.
#821 
Adding configuration item `spring.cloud.sentinel.filter.enabled=false` by `EnvironmentPostProcessor`
in module `sentinel-gateway`.
None

Disable sentinel web filters.

---

spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboLoadBalancedRestTemplateAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceBuilder.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceLocator.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/diagnostics/analyzer/NacosConnectionFailureAnalyzer.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosConfigEndpoint.java

* The `NacosPropertySourceLocator` check dataId file extension code is too redundant
*  decide file extension use `indexof()` instead of `endwith()` maybe cause a bug
* some spell check
NONE

Optimize code and fix #841

---

spring-cloud-alicloud-oss/src/main/java/com/alibaba/alicloud/oss/resource/OssStorageResource.java

Optional value should only be accessed after calling isPresent()

Optional value should only be accessed after calling isPresent()

---

spring-cloud-alibaba-docs/src/main/asciidoc/nacos-config.adoc

fix docs typo

---

spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryClient.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosServerList.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/NacosDiscoveryClientTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/ribbon/NacosServerListTests.java

support nacos group in nacos discovery
#593 #540 #580 
add nacos discovery group 
run examples

support nacos discovery group

---

spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryClient.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosServerList.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/NacosDiscoveryClientTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/ribbon/NacosServerListTests.java

 nacos discovery support group

---

spring-cloud-alibaba-dubbo/README_CN.md

Update Dubbo README

---

spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosConfigEndpointAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosConfigHealthIndicator.java
spring-cloud-alibaba-nacos-config/src/test/java/com/alibaba/cloud/nacos/endpoint/NacosConfigEndpointTests.java

The `NacosConfigHealthIndicator` has a bug with always in up state. 
Fixes #855

Check nacos config health use configService

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/sentinel.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/sentinel.adoc
spring-cloud-alibaba-examples/ans-example/ans-consumer-feign-example/src/main/java/com/alibaba/cloud/examples/HomeController.java
spring-cloud-alibaba-examples/ans-example/ans-consumer-ribbon-example/src/main/java/com/alibaba/cloud/examples/HomeController.java
spring-cloud-alibaba-examples/ans-example/ans-provider-example/src/main/java/com/alibaba/cloud/examples/EchoController.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/java/com/alibaba/cloud/examples/ConsumerApplication.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/java/com/alibaba/cloud/examples/TestController.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/src/main/java/com/alibaba/cloud/examples/ProviderApplication.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-spring-cloud-config-client/src/main/java/com/alibaba/cloud/examples/GetConfigController.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme-zh.md
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme.md
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-provider-example/src/main/java/com/alibaba/cloud/examples/ProviderApplication.java
spring-cloud-alibaba-examples/seata-example/account-service/src/main/java/com/alibaba/cloud/examples/AccountController.java
spring-cloud-alibaba-examples/seata-example/business-service/src/main/java/com/alibaba/cloud/examples/BusinessApplication.java
spring-cloud-alibaba-examples/seata-example/business-service/src/main/java/com/alibaba/cloud/examples/HomeController.java
spring-cloud-alibaba-examples/seata-example/order-service/src/main/java/com/alibaba/cloud/examples/OrderController.java
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/java/com/alibaba/cloud/examples/StorageController.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/java/com/alibaba/cloud/examples/TestController.java

We can use the more advanced Spring API provided to us to make the code clearer and more readable.

Use Spring advanced API make design more clearer

---

spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/java/com/alibaba/cloud/examples/ConsumerApplication.java

remove unused import statement

remove unused import statement

---

spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/sentinel-dubbo-consumer-example/src/main/java/com/alibaba/cloud/examples/FooServiceConsumer.java
spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelBeanPostProcessor.java

It also means compatibility modifications about SpringBoot version from 2.1.x to 2.2.x.

some compatibility modifications about Hoxton

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/rocketmq.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/rocketmq.adoc

将“DELAY”字符串改成常量形式。
最近有人问我DELAY的值是什么意思，是时间还是等级？
我觉得文档会让人误解。改成常量的方式就知道是DELAY的等级了。

Modify magic string to constant.

---

README.md

resolve https://github.com/alibaba/spring-cloud-alibaba/issues/933

Fix Duboo typo

---

spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboMetadataAutoConfiguration.java
spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/DubboServiceMetadataRepository.java
spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/MetadataServiceInstanceSelector.java

another way to customize getting service instance in service subscribe and fixes #908.
Fixes [#908 ](https://github.com/alibaba/spring-cloud-alibaba/issues/908)

another way to customize getting service instance in service subscribe and fixes #908.

---

README.md
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigManager.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigProperties.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceLocator.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosDataParserHandler.java
spring-cloud-alibaba-nacos-config/src/test/java/com/alibaba/cloud/nacos/NacosConfigurationNoSuffixTest.java
spring-cloud-circuitbreaker-sentinel/src/test/java/com/alibaba/cloud/circuitbreaker/sentinel/ReactiveSentinelCircuitBreakerIntegrationTest.java
spring-cloud-circuitbreaker-sentinel/src/test/java/com/alibaba/cloud/circuitbreaker/sentinel/SentinelCircuitBreakerIntegrationTest.java

Currently, it is rather rigid, I've done compatibility, and it's going to be dynamic
and the subsequent nacos can support the optimization of suffix reading into dynamic
#921

support reading nacos config with no suffix dataid &  enhance NacosConfigProperties

---

spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/java/com/alibaba/cloud/examples/Application.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigManager.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosNamingManager.java

fix issue #859 
Because of the spring bean refresh mechanism, so I think to maintain a singleton object caching is more appropriate to hold the Service

fix(nacos): fix issue #859

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-dubbo/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/pom.xml

As titled.
Refer https://spring.io/blog/2019/09/12/spring-cloud-greenwich-sr3-released.

Updates to spring cloud Greenwich.SR3

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-docs/src/main/asciidoc-zh/sidecar.adoc
spring-cloud-alibaba-docs/src/main/asciidoc-zh/spring-cloud-alibaba.adoc
spring-cloud-alibaba-examples/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/node-service.js
spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/spring-cloud-alibaba-sidecar-consul-example/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/spring-cloud-alibaba-sidecar-consul-example/src/main/java/com/alibaba/cloud/sidecar/DemoApplication.java
spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/spring-cloud-alibaba-sidecar-consul-example/src/main/resources/application.yml
spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/spring-cloud-alibaba-sidecar-nacos-example/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/spring-cloud-alibaba-sidecar-nacos-example/src/main/java/com/alibaba/cloud/sidecar/DemoApplication.java
spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/spring-cloud-alibaba-sidecar-nacos-example/src/main/resources/application.yml
spring-cloud-alibaba-sidecar/pom.xml
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarAutoConfiguration.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarDiscoveryClient.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarHealthChecker.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarHealthIndicator.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarProperties.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/consul/SidecarConsulAutoConfiguration.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/consul/SidecarConsulAutoRegistration.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/consul/SidecarConsulDiscoveryClient.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosAutoConfiguration.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosDiscoveryClient.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosDiscoveryProperties.java
spring-cloud-alibaba-sidecar/src/main/resources/META-INF/spring.factories
spring-cloud-starter-alibaba/pom.xml
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-sidecar/pom.xml

Add module Spring Cloud Alibaba Sidecar

Add module Spring Cloud Alibaba Sidecar

---

spring-cloud-alibaba-sidecar/pom.xml
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarHealthChecker.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarProperties.java

configuration item: 
`sidecar.health-check-interval`

Add sidecar health check interval configuration item.

---

spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-config-server/pom.xml
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-config/pom.xml
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-discovery/pom.xml
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-seata/pom.xml
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-sentinel/pom.xml
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-sidecar/pom.xml
spring-cloud-starter-alibaba/spring-cloud-starter-dubbo/pom.xml
spring-cloud-starter-alicloud/spring-cloud-starter-alicloud-acm/pom.xml
spring-cloud-starter-alicloud/spring-cloud-starter-alicloud-ans/pom.xml
spring-cloud-starter-alicloud/spring-cloud-starter-alicloud-oss/pom.xml
spring-cloud-starter-alicloud/spring-cloud-starter-alicloud-schedulerx/pom.xml
spring-cloud-starter-alicloud/spring-cloud-starter-alicloud-sms/pom.xml

update to correct starter definitions

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/seata-example/account-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/account-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/business-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/order-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/order-service/src/main/resources/registry.conf
spring-cloud-alibaba-examples/seata-example/readme-zh.md
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/resources/file.conf
spring-cloud-alibaba-examples/seata-example/storage-service/src/main/resources/registry.conf

Signed-off-by: slievrly <slievrly@163.com>
update seata version and sample

update seata version and sample

---

spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/pom.xml

on branch finchley
An error occurred when I was about to run the spring-cloud-alibaba-dubbo-example project.
`java.lang.NoClassDefFoundError: org/apache/dubbo/config/spring/context/config/NamePropertyDefaultValueDubboConfigBeanCustomizer
at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_181]
at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_181]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_181]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_181]
at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_181]
at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_181]
at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_181]
at …

modify examples dubbo version

---

spring-cloud-alibaba-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboServiceDiscoveryAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/pom.xml
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryClient.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosServiceDiscovery.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/configclient/NacosDiscoveryClientConfigServiceBootstrapConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/reactive/NacosReactiveDiscoveryClient.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/reactive/NacosReactiveDiscoveryClientConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistryAutoConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/main/resources/META-INF/spring.factories
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/NacosDiscoveryPropertiesServerAddressBothLevelTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/NacosDiscoveryPropertiesServerAddressTopLevelTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryAutoConfigurationTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfigurationTest.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/discovery/NacosServiceDiscoveryTest.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/discovery/reactive/NacosReactiveDiscoveryClientConfigurationTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/discovery/reactive/NacosReactiveDiscoveryClientTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/registry/NacosAutoServiceRegistrationIpNetworkInterfaceTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/registry/NacosAutoServiceRegistrationIpTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/registry/NacosAutoServiceRegistrationManagementPortTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/registry/NacosAutoServiceRegistrationPortTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/registry/NacosAutoServiceRegistrationTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientConfigurationTests.java
spring-cloud-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosAutoConfiguration.java

Support Nacos reactive service discovery

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/sentinel-dubbo-consumer-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-dubbo-example/sentinel-dubbo-provider-example/pom.xml

**Modules :**  
* spring-cloud-alibaba-dependencies
* sentinel-example
The example dependencies should not be relied on by the core dependencies ,The dependency is reversed.

fix dependencies

---

spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme.md

You could use absolute path when you use File datasource & fat jar.

add some warnings for classpath file datasource

---

spring-cloud-circuitbreaker-sentinel/src/main/java/com/alibaba/cloud/circuitbreaker/sentinel/ReactiveSentinelCircuitBreakerAutoConfiguration.java
spring-cloud-circuitbreaker-sentinel/src/main/java/com/alibaba/cloud/circuitbreaker/sentinel/SentinelCircuitBreakerAutoConfiguration.java
spring-cloud-circuitbreaker-sentinel/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Add property to disable Sentinel auto-configuration

---

spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/scg/SentinelSCGAutoConfiguration.java

correct the log print wrong content
Fixes alibaba#1114
just change `fallbackProperties.getResponseStatus()` to `fallbackProperties.getResponseBody()`
define `spring.cloud.sentinel.scg.fallback` in yml file , when app starts , will see logs in console

correct the log

---

spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigProperties.java
spring-cloud-alibaba-nacos-config/src/main/resources/META-INF/additional-spring-configuration-metadata.json
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-nacos-discovery/src/main/resources/META-INF/additional-spring-configuration-metadata.json
spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/NacosDataSourceProperties.java

Add default values for some configuration items

---

spring-cloud-alibaba-seata/pom.xml
spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/feign/SeataFeignBlockingLoadBalancerClient.java
spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/feign/SeataFeignObjectWrapper.java

Support seata new feign loadbalancer
fix issue #1092

Support seata feign loadbalancer

---

spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/feign/SeataBeanPostProcessor.java

Signed-off-by: slievrly <slievrly@163.com>
fix SeataBeanPostProcessor can't use cglib proxy
https://github.com/seata/seata/issues/1976#issue-531050818

bugfix: SeataBeanPostProcessor can't use cglib proxy

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-nacos-config/pom.xml
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigProperties.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceLocator.java
spring-cloud-alibaba-nacos-discovery/pom.xml
spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/NacosDataSourceProperties.java

support more config for Nacos
fix #1078

support more config for Nacos

---

spring-cloud-alibaba-dubbo/src/test/java/com/alibaba/cloud/dubbo/http/matcher/ConsumeMediaTypeExpressionTest.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-spring-cloud-gateway-example/src/main/java/com/alibaba/cloud/examples/MySCGConfiguration.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-webflux-example/src/main/java/com/alibaba/cloud/examples/MyConfiguration.java
spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/FallbackProperties.java
spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/scg/SentinelSCGAutoConfiguration.java

Many of the properties in `Spring Cloud Alibaba Sentinel Gateway` module  deprecated
It will be removed in the near future. 
So we should use the new properties
NO 
spring 5.2 fromObject  --> fromValue
MediaType.APPLICATION_JSON_UTF8  ---> MediaType.APPLICATION_JSON
run `sentinel-spring-cloud-gateway-example`
```
curl http://localhost:18085/product/baz   
```
return  http code 444 and 1234 , Everything is all right

replace code properties that have expired

---

spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientConfiguration.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientPropertyOverrideNIWSserverTests.java
spring-cloud-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientPropertyOverrideTests.java

Suport Ribbon ConfigurationBasedServerList

---

spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/java/com/alibaba/cloud/examples/Application.java
spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/resources/bootstrap.properties
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigBootstrapConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigManager.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigProperties.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosPropertySourceRepository.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySource.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceBuilder.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceLocator.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosConfigEndpointAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/refresh/NacosContextRefresher.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/refresh/NacosRefreshHistory.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/refresh/NacosRefreshProperties.java
spring-cloud-alibaba-nacos-config/src/main/resources/META-INF/additional-spring-configuration-metadata.json
spring-cloud-alibaba-nacos-config/src/test/java/com/alibaba/cloud/nacos/NacosConfigurationNewTest.java

Solve three problems:
1. nacos config shared-dataids cont select group
2. shared-dataids and ext-config can support profile recognition
3. fix part of original unreasonable design
#982
#978

[issue #982 & issue #978]enhance nacos config

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/pom.xml
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/java/com/alibaba/cloud/examples/WebMvcConfiguration.java
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/src/main/resources/templates/errorPage.html
spring-cloud-alibaba-sentinel/pom.xml
spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelConstants.java
spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelProperties.java
spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelWebAutoConfiguration.java
spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelAutoConfiguration.java
spring-cloud-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/endpoint/SentinelEndpoint.java
spring-cloud-alibaba-sentinel/src/main/resources/META-INF/additional-spring-configuration-metadata.json
spring-cloud-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/SentinelAutoConfigurationTests.java
spring-cloud-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/SentinelBeanAutowiredTests.java

- Upgrade Sentinel to 1.7.1
- Introduce `SentinelWebInterceptor` to replace `CommonFilter`
fixed #1168

[Upgrade] Upgrade Sentinel and Enhance

---

spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigAutoConfiguration.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySourceBuilder.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/AbstractNacosDataParser.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosDataJsonParser.java
spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosDataXmlParser.java
spring-cloud-alibaba-nacos-config/src/test/java/com/alibaba/cloud/nacos/NacosConfigurationXmlJsonTest.java

- Resolve the type erase caused by loading Nacos data
fixed #1162

[Bugfix] Resolve the type erase caused by loading Nacos data

---

spring-cloud-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosPropertySourceRepository.java
spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/AcmPropertySourceRepository.java
spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/bootstrap/AcmConfigBootStrapConfiguration.java
spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/bootstrap/AcmPropertySource.java
spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/bootstrap/AcmPropertySourceBuilder.java
spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/bootstrap/AcmPropertySourceLocator.java
spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/endpoint/AcmEndpoint.java
spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/endpoint/AcmEndpointAutoConfiguration.java
spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/endpoint/AcmHealthIndicator.java
spring-cloud-alicloud-acm/src/main/java/com/alibaba/alicloud/acm/refresh/AcmContextRefresher.java
spring-cloud-alicloud-acm/src/main/resources/META-INF/spring.factories
spring-cloud-alicloud-acm/src/test/java/com/alibaba/alicloud/acm/endpoint/AcmEndpointTests.java

- optimize Acm module base Spring Cloud Common 2.2.1
- solved `NacosPropertySourceRepository` data is not updated when data changes are monitored

[optimize] Acm enhance base Spring Cloud Common 2.2.1

---

spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/reactive/NacosReactiveDiscoveryClient.java

Avoid impacting other non blocking process.

Use the bounded elastic thread pool when subscribe.

---

spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/zuul/SentinelZuulProperties.java

fix Sentinel zuul NPE
fix issue #1213

fix Sentinel zuul NPE

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/resources/bootstrap.properties
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/java/com/alibaba/cloud/examples/ConsumerApplication.java
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-sclb-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-provider-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-spring-cloud-config-client-example/src/main/resources/bootstrap.yml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-spring-cloud-config-server-example/src/main/resources/application.yml
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-reactivediscovery-consumer-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-discovery-example/src/main/resources/application.properties
spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-provider-example/src/main/resources/application.properties
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigProperties.java
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-config/src/main/resources/META-INF/additional-spring-configuration-metadata.json
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-starter-alibaba/spring-cloud-starter-alibaba-nacos-discovery/src/main/resources/META-INF/additional-spring-configuration-metadata.json

- upgrade Nacos client version to 1.2.0
- provide nacos authentication configuration items
example:
```
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
```
refer #1227

Upgrade Nacos client version

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosConfigEndpointAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/resources/META-INF/additional-spring-configuration-metadata.json
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/config/RocketMQBinderHealthIndicatorAutoConfiguration.java

Use @ConditionalOnEnabledHealthIndicator to conditional assembly.
- `NacosConfigHealthIndicator`
- `SidecarHealthIndicator`
- `RocketMQBinderHealthIndicator`
- `AcmHealthIndicator`
Fixes https://github.com/alibaba/spring-cloud-alibaba/issues/1276

[Optimize] Use @ConditionalOnEnabledHealthIndicator to conditional assembly

---

spring-cloud-alibaba-dependencies/pom.xml

- Upgrade nacos-client version to 1.2.1

upgrade nacos-client version to 1.2.1 based on SC.Finchley

---

spring-cloud-alibaba-dependencies/pom.xml

- Upgrade Nacos Client version to 1.2.1

upgrade nacos-client version to 1.2.1 based on SC.Greenwich

---

spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/README_CN.md

Readme link error fix
#ref https://github.com/alibaba/spring-cloud-alibaba/issues/1214

fix document link error

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-seata/src/main/java/com/alibaba/cloud/seata/feign/hystrix/SeataHystrixConcurrencyStrategy.java

optimize: optimize SeataHystrixConcurrencyStrategy
- support Sleuth、Security context
- support request header

optimize: optimize SeataHystrixConcurrencyStrategy

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/pom.xml
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/ConsulDataSourceProperties.java
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/DataSourcePropertiesConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/RedisDataSourceProperties.java
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/factorybean/ConsulDataSourceFactoryBean.java
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/resources/META-INF/sentinel-datasource.properties
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-seata/src/main/java/com/alibaba/cloud/seata/feign/hystrix/SeataHystrixConcurrencyStrategy.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/DubboServiceMetadataRepository.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/AbstractSpringCloudRegistry.java

https://github.com/alibaba/spring-cloud-alibaba/issues/1363

[Feature] Synchronizing code to Spring Cloud Alibaba finchley branch

---

spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/resources/application.yml
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-provider-example/src/main/resources/application.yml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-client-sample/src/main/resources/bootstrap.yaml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-consumer-sample/src/main/resources/bootstrap.yaml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-sample/src/main/resources/bootstrap.yaml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-web-sample/src/main/resources/bootstrap.yaml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-server-sample/src/main/resources/bootstrap.yaml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-servlet-gateway-sample/src/main/resources/bootstrap.yaml
spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/spring-cloud-alibaba-sidecar-nacos-example/src/main/resources/application.yml
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/test/resources/bootstrap.yaml

https://github.com/alibaba/spring-cloud-alibaba/issues/1365

Synchronizing samples to Spring Cloud Alibaba finchley branch

---

pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboServiceRegistrationNonWebApplicationAutoConfiguration.java

fix: https://github.com/alibaba/spring-cloud-alibaba/issues/1383
move flatten-maven-plugin from profile "release" to build

fix issue: https://github.com/alibaba/spring-cloud-alibaba/issues/1383

---

spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/spring-cloud-alibaba-sidecar-nacos-example/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-sidecar-examples/spring-cloud-alibaba-sidecar-nacos-example/src/main/resources/application.yml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosDiscoveryClient.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosDiscoveryProperties.java

- Only register sidecar heterogeneous service instances.
Fixed #1370

sidecar enhance

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosDataPropertiesParser.java

- Remove configuration item spaces
Fixed #1427

NacosDataPropertiesParser enhance

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosServiceDiscovery.java

fix com.alibaba.cloud.nacos.discovery.NacosServiceDiscovery.hostToServiceInstance(NacosServiceDiscovery.java:95) potential NullPointerException
Fixes #1535

[issue #1535 ]fix NacosServiceDiscovery.hostToServiceInstance  method potential NullPointerException

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/pom.xml

Enhance dependency
Fixed #1544 
Fixed #1543 
Fixed #1542

[Enhancement] spring-cloud-starter-alibaba-sentinel dependency

---

spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme-zh.md
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme.md

fix nacos-discovery-example readme doc

fix nacos-discovery-example readme doc

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosRule.java

add search instance by group
support instance in customer group
Fixes #1480 #1482 
add group to find instance function
check customer group

[Optimize]: NacosRule support group

---

spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-sample/src/main/resources/bootstrap.yaml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosServiceDiscovery.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/resources/META-INF/additional-spring-configuration-metadata.json

[enhance issue #1478 ]支持注册非活动节点

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/NacosConfigProperties.java

[issue #1418 ]shareIds和拉取nacos的顺序不对

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc

docs: update nacos-config.adoc

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosWatch.java

Fix typo in NacosWatch

---

spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/RedisDataSourceProperties.java

'修复字段masterId判断bug'

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboServiceAutoConfiguration.java

Dubbo Update 

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/registry/MockNamingService.java

[Infrastructure] Upgrading the dependencies of nacos

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/nacos/SidecarNacosDiscoveryProperties.java

https://github.com/alibaba/spring-cloud-alibaba/issues/1453

[Nacos] Adding the destroy lifecycle callback for NamingService

---

spring-cloud-alibaba-dependencies/pom.xml

Signed-off-by: slievrly <slievrly@163.com>
[Seata]: upgrade seata version to 1.3.0
https://github.com/alibaba/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/seata-example
http://localhost:18081/seata/rest
http://localhost:18081/seata/feign
valid case:

[Seata]: upgrade seata version to 1.3.0

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/scg/SentinelSCGAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-gateway/src/main/java/com/alibaba/cloud/sentinel/gateway/zuul/SentinelZuulAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelAutoConfiguration.java

- upgrade Sentinel Version to 1.8.0
Fixed #1653

[Enhancement] Upgrade Sentinel Version to 1.8.0

---

spring-cloud-alibaba-starters/spring-cloud-circuitbreaker-sentinel/src/test/java/com/alibaba/cloud/circuitbreaker/sentinel/ReactiveSentinelCircuitBreakerIntegrationTest.java
spring-cloud-alibaba-starters/spring-cloud-circuitbreaker-sentinel/src/test/java/com/alibaba/cloud/circuitbreaker/sentinel/SentinelCircuitBreakerIntegrationTest.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/SentinelAutoConfigurationTests.java

Signed-off-by: Eric Zhao <sczyh16@gmail.com>
Update test cases of spring-cloud-circuitbreaker-sentinel to fix test failure (due to the breaking changes regarding circuit breaking in Sentinel 1.8.0).
NONE
Run the test cases.
Nope.

Update test cases of spring-cloud-circuitbreaker-sentinel

---

spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboMetadataAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboServiceDiscoveryAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/env/DubboCloudProperties.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/env/DubboNonWebApplicationEnvironmentPostProcessor.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/DubboServiceMetadataRepository.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/RandomServiceInstanceSelector.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/ServiceInstanceSelector.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/AbstractSpringCloudRegistry.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/DubboCloudRegistry.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/SpringCloudRegistry.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/SpringCloudRegistryFactory.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/service/DubboGenericServiceFactory.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/service/DubboMetadataServiceProxy.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/util/DubboCloudConstants.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/util/DubboMetadataUtils.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/resources/META-INF/dubbo/default/actuator-endpoints.properties
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/resources/META-INF/spring.factories

Revision of 2.1.2.release version #1529 bug
Fixes #1529
1. Start [spring cloud Dubbo client sample]
2. [spring cloud Dubbo server sample] Project configuration properties [dubbo.cloud.subscribed-services] Add an empty service
3.Start [spring cloud Dubbo server sample]
4. Access interface localhost:8080/echo

fix bug 1529 Project version 2.1.2.release

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarHealthChecker.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarInstanceCache.java

- Solve the problem of sidecar repeated timing registration.
- After the proxy service instance information changes, re-register.
Fixes #1685

[enhancement] Sidecar health detection optimization

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosRegistration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosRegistrationCustomizer.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistryAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/registry/NacosRegistrationCustomizerTest.java

方便用户自定义 NacosRegistrationCustomizer 实现，向 NacosRegistration 中注入配置。

add NacosRegistrationCustomizer

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-seata/src/main/java/com/alibaba/cloud/seata/web/SeataHandlerInterceptor.java

judging xid status to avoid repeated processing
transactionPropagationIntercepter with seataHandlerInterceptor conflict
relevance: https://github.com/seata/seata/pull/2597
Fixes #1353 
sequence:
SeataHandlerInterceptor#preHandle->TransactionPropagationIntercepter#preHandle->TransactionPropagationIntercepter#postHandle->SeataHandlerInterceptor#afterCompletion

 judging xid status to avoid repeated processing

---

pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosConfigEndpointAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosDiscoveryEndpointAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/endpoint/SentinelEndpointAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/actuate/DubboMetadataEndpointAutoConfiguration.java

Adapt to Spring Cloud version Hoxton.SR8

---

spring-cloud-alibaba-examples/seata-example/order-service/src/main/java/com/alibaba/cloud/examples/OrderApplication.java

correct the spelling of "oder"

correct spelling

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosWatch.java

NacosWatch to update local metadata

---

spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/factorybean/NacosDataSourceFactoryBean.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosServiceManager.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/event/NacosDiscoveryInfoChangedEvent.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/event/NacosDiscoveryInfoInitializedEvent.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosAutoServiceRegistration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistryAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosServerList.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/ribbon/NacosServerListTests.java

Fix some bugs for 2.2.2.RELEASE

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosServiceDiscovery.java

[Enhancement] NacosDiscoveryClient always getNamingservice from Nacosmanager

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosServiceDiscovery.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosWatch.java

[Enhancement] NacosWatch keep publish HeartbeatEvent

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml

- Nacos Client 1.3.2
- RocketMQ Spring Boot Starter 2.1.1

[Infrastructure] Upgrading the dependencies

---

spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/annotation/DubboTransported.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboServiceDiscoveryAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/http/matcher/AbstractHttpRequestMatcher.java

[JavaDoc] Fix issues

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosConfigEndpoint.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/endpoint/NacosDiscoveryEndpoint.java

spring cloud alibaba 2.2.3
spring boot 2.3.4
When the service starts, the above waring prompt will be thrown。
This is because the name contains illegal characters (-) when defining the name
NO
The modified name does not contain illegal characters，
**Don't use camel case naming,because the official style**
Only need to output log at startup

fix EndpointId logWarning

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-seata/src/main/java/com/alibaba/cloud/seata/feign/hystrix/SeataHystrixConcurrencyStrategy.java

bugfix: fix compatibility issue with 'seata-all-1.4.0'.
问题修复：修复与seata-all的1.4.0版本的兼容性问题。
Fixes #1800

bugfix: fix compatibility issue with 'seata-all-1.4.0'

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosWatch.java

Optimize the way to get NacosWatch#ThreadPoolTaskScheduler

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/configclient/NacosDiscoveryClientConfigServiceBootstrapConfiguration.java

Fix Issue #1791

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosDiscoveryProperties.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosRegistration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/registry/NacosAutoServiceRegistrationTests.java

[ISSUE-#1877] Fix nacos heart beat unit, second to millisecond.

---

spring-cloud-alibaba-dependencies/pom.xml

[ISSUE-#1875] Upgrade nacos-client version to 1.4.0

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java

…up name
Fixes #1893 ， fix the issue invalid method used `com.alibaba.nacos.api.naming.NamingMaintainService#updateInstance(java.lang.String, java.lang.String, com.alibaba.nacos.api.naming.pojo.Instance)` in method `com.alibaba.cloud.nacos.registry.NacosServiceRegistry#setStatus`
Fixes #1893 
change the use of method
use spring /actuator/service-registry to change the service successfully.

[Fix] Spring cloud alibaba 2.2.3版本使用端点/actuator/service-registry注销服务注册问题

---

spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/DubboCloudRegistry.java

https://github.com/apache/dubbo/issues/7079
npe problem
NONE
debug
I don't know how to write test cases
I tested it with a demo:
https://github.com/seedscoder/spring-cloud-dubbo-grpc
But I keep getting errors when I use the snapshot version:
java.lang.ClassNotFoundException: org.springframework.cloud.client.serviceregistry.Registration
What do I think is the reason I didn't get it right, unrelated to the bug fix

Fix bug: NPE Exception.

---

README-zh.md
README.md
pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-docs/src/main/asciidoc-zh/dependency-management.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/dependency-management.adoc
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-servlet-gateway-sample/src/main/java/com/alibaba/cloud/dubbo/gateway/DubboGatewayServlet.java
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosRule.java

upgrade SCA version to 2.2.4.RELEASE
update nacos client version to 1.4.1

version update to 2.2.4

---

spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/java/com/alibaba/cloud/examples/Application.java
spring-cloud-alibaba-examples/nacos-example/nacos-config-example/src/main/resources/bootstrap.properties
spring-cloud-alibaba-examples/rocketmq-example/rocketmq-consume-example/src/main/java/com/alibaba/cloud/examples/RocketMQConsumerApplication.java

updated examples

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/AbstractPropertySourceLoader.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosDataParserHandler.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosJsonPropertySourceLoader.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosXmlPropertySourceLoader.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/utils/NacosConfigUtils.java

fixed chinese garbled for nacos-config

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/utils/NacosConfigUtils.java

fixed - all unicode encoding , exclude base latin letter.

---

README.md
spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/readme.md
spring-cloud-alibaba-examples/rocketmq-example/readme.md

Two URLs in under the spring-cloud-alibaba-examples are wrongly set.
I replace one with the right URL to download, one with the right one to open console.
I test on my local Mac.
NONE.

修改了两个错误的URL

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-consumer-sample/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-sample/pom.xml
spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples/spring-cloud-dubbo-provider-web-sample/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config-server/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/pom.xml

Use spring.cloud.version@spring-cloud-dependencies instead of the version number of each component

Use spring.cloud.version instead of the version number of each component

---

spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/endpoint/SentinelHealthIndicator.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/test/java/com/alibaba/cloud/sentinel/SentinelAutoConfigurationTests.java

Upgrade Sentinel to 1.8.1

---

spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/readme-zh.md
spring-cloud-alibaba-examples/sentinel-example/sentinel-feign-example/sentinel-feign-consumer-example/src/main/resources/application.yml

Improve the sentinel sample feature

sentinel示例，添加sentinel配置，实现sentinel示例功能，以及运行说明。

---

spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/env/DubboCloudProperties.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/DubboCloudRegistry.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/ReSubscribeMetadataJob.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/ServiceInstanceChangeListener.java
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/registry/SpringCloudRegistryFactory.java

https://github.com/alibaba/spring-cloud-alibaba/issues/2070
* Use a separate interface to solve the sorting problem
* Use a separate thread for asynchronous retry when subscription service failure

resolve @order not effect when handle ServiceInstanceChangedEvent

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc

add Wiki 文档“配置的优先级”存在容易混淆的表述 #1874

---

PULL_REQUEST_TEMPLATE.md
spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc

fix words that we can read more friendly
no
when I read wiki-document, I find it
By google translate

fix word "namespae" -> "namespace"

---

spring-cloud-alibaba-dependencies/pom.xml

update nacos-client to 1.4.2, resolve problem https://github.com/alibaba/nacos/issues/5291

update nacos-client to 1.4.2

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelProtectInterceptor.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/feign/SentinelInvocationHandler.java

Use the sentinel in a safe way

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosDiscoveryClientConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/discovery/NacosWatch.java

[Enhancement] NacosWatch use a separate thread pool

---

spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/autoconfigure/DubboServiceRegistrationAutoConfiguration.java

attach metadata before register
fix following issue:
- close #2157

fix register metadata to consul

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/NacosServiceManager.java

Enhance Nacos shutdown, NacosServiceRegistry#close()

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/CustomHealthCheckHandler.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarHealthChecker.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar/src/main/java/com/alibaba/cloud/sidecar/SidecarInstanceInfo.java

- Service instance status changes to provide scalable processing, such as custom notification alerts.

[Feature] SidecarHealthChecker add CustomerHandler

---

pom.xml
spring-cloud-alibaba-dependencies/pom.xml
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/test/java/com/alibaba/cloud/nacos/ribbon/NacosRibbonClientPropertyOverrideTests.java

Upgrade Nacos client version to 2.0.3

---

pom.xml
spring-cloud-alibaba-docs/src/main/asciidoc-zh/rocketmq.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/rocketmq.adoc
spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/RocketMQBinderUtils.java
spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/RocketMQMessageChannelBinder.java
spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/config/RocketMQComponent4BinderAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/consuming/RocketMQListenerBindingContainer.java
spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/properties/RocketMQBinderConfigurationProperties.java
spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/test/java/com/alibaba/cloud/stream/binder/rocketmq/RocketMQAutoConfigurationTests.java

升级rocketmq-spring-boot-starter版本，商业版消息轨迹无需手动配置轨迹topic

---

spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/config/RocketMQComponent4BinderAutoConfiguration.java

[rocketmq]fix variable judgment bug

---

README-zh.md
README.md

Optimize README format.
NONE
1. Using Chinese `、` instead of `, ` symbol for consistency.
2. Fix markdown code block gramma error.
Check the optimized markdown document.
NONE

Optimize README format.

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistryAutoConfiguration.java

Change NacosServiceManager injection mode to constructor injection
Fix #2271

Change NacosServiceManager injection mode to constructor injection

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/pom.xml

Use the legacy bootstrap way in newer spring-cloud version
#2300 #2048 
All about this pr in issue #2300

fixup: issue#2300

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelWebAutoConfiguration.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelWebMvcConfigurer.java

A separate configuration class solves the problem of loop dependencies
- `SentinelWebMvcConfigurer`
Fixes #2323

fix issue#2323

---

spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/config/NacosDataSourceProperties.java
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/factorybean/NacosDataSourceFactoryBean.java
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/test/java/com/alibaba/cloud/sentinel/datasource/NacosDataSourceFactoryBeanTests.java
spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/test/java/com/alibaba/cloud/sentinel/datasource/NacosDataSourcePropertiesTests.java

NacosDataSourceProperties support for contextPath configuration items

---

spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/autoconfigurate/ExtendedBindingHandlerMappingsProviderConfiguration.java

```shell
[INFO] --- maven-checkstyle-plugin:3.0.0:check (checkstyle-validation) @ spring-cloud-starter-stream-rocketmq ---
[INFO] 开始检查……
[ERROR] /Users/xxx/Git/github/spring-cloud-alibaba/spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/autoconfigurate/ExtendedBindingHandlerMappingsProviderConfiguration.java:59: 需要一个 Javadoc注释 @return 。 [JavadocMethod]
检查完成。
[INFO] ------------------------------------------------------------------------
```

fix the checkstyle plugin check error

---

spring-cloud-alibaba-docs/src/main/asciidoc-zh/nacos-config.adoc
spring-cloud-alibaba-docs/src/main/asciidoc/nacos-config.adoc
spring-cloud-alibaba-starters/spring-cloud-starter-dubbo/src/main/java/com/alibaba/cloud/dubbo/metadata/repository/DubboServiceMetadataRepository.java

Update the project link to: `https://github.com/alibaba/spring-cloud-alibaba`

Update documentation and code comment links

---

spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/client/NacosPropertySource.java
spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/test/java/com/alibaba/cloud/nacos/NacosFileExtensionTest.java

支持nacos配置文件使用YAML并包含"---"分隔符号。
#issue：https://github.com/alibaba/spring-cloud-alibaba/issues/2328

[Enhancement] Support for obtaining configuration data with delimiters from Nacos

---

spring-cloud-alibaba-starters/spring-cloud-alibaba-sentinel-datasource/src/main/java/com/alibaba/cloud/sentinel/datasource/converter/SentinelConverter.java

没有配置规则是很正常的，例如用户侧做了全局规则实现，这里频繁刷warn日志无法控制.

Lower log level
